#!/usr/bin/env node
/**
 * Reads secrets from .env.local (local dev) or process.env (CI/CD)
 * and writes src/environments/environment.ts + environment.development.ts.
 *
 * CI usage: set GOOGLE_API_KEY, GOOGLE_SHEET_ID, and VACATION_API_URL
 *           as environment variables (GitHub Actions secrets) before running.
 */
const fs = require('fs');
const path = require('path');

function readEnvLocal() {
  const envPath = path.join(__dirname, '..', '.env.local');
  if (!fs.existsSync(envPath)) return {};
  const vars = {};
  fs.readFileSync(envPath, 'utf-8')
    .split('\n')
    .forEach(line => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) return;
      const eq = trimmed.indexOf('=');
      if (eq < 0) return;
      const key = trimmed.slice(0, eq).trim();
      const val = trimmed.slice(eq + 1).trim();
      vars[key] = val;
    });
  return vars;
}

const local = readEnvLocal();
const apiKey        = local.GOOGLE_API_KEY    ?? process.env.GOOGLE_API_KEY    ?? '';
const sheetId       = local.GOOGLE_SHEET_ID   ?? process.env.GOOGLE_SHEET_ID   ?? '';
const vacationApiUrl = local.VACATION_API_URL  ?? process.env.VACATION_API_URL  ?? '';
const apiNinjasKey  = local.API_NINJAS_KEY    ?? process.env.API_NINJAS_KEY    ?? '';

if (!apiKey || !sheetId) {
  console.warn('[setup-env] WARNING: GOOGLE_API_KEY or GOOGLE_SHEET_ID is empty.');
}
if (!vacationApiUrl) {
  console.warn('[setup-env] WARNING: VACATION_API_URL is empty — vacation submission will not work.');
}
if (!apiNinjasKey) {
  console.warn('[setup-env] WARNING: API_NINJAS_KEY is empty — daily quote will not work.');
}

const envDir = path.join(__dirname, '..', 'src', 'environments');
fs.mkdirSync(envDir, { recursive: true });

const tpl = (prod) => `// Auto-generated by scripts/setup-env.js — do not edit manually.
export const environment = {
  production: ${prod},
  googleApiKey: '${apiKey}',
  googleSheetId: '${sheetId}',
  vacationApiUrl: '${vacationApiUrl}',
  apiNinjasKey: '${apiNinjasKey}',
};
`;

fs.writeFileSync(path.join(envDir, 'environment.ts'), tpl(true));
fs.writeFileSync(path.join(envDir, 'environment.development.ts'), tpl(false));
console.log('[setup-env] Environment files written to src/environments/');
